name: Release

on:
  workflow_dispatch:
    inputs:
      target_version:
        type: string
        required: false
        description: "mod version | empty = next option"
      update_type:
        type: choice
        required: false
        description: "update type"
        default: "minor"
        options:
          - "major"
          - "minor"
          - "patch"
          - "none"
      release_type:
        type: choice
        required: true
        description: "type of release"
        default: "release"
        options:
          - "alpha"
          - "beta"
          - "release"
      debug:
        type: boolean
        required: false
        default: false
        description: "enable debug mode (GitHub only)"

jobs:
  redirect:
    uses: AlmostReliable/.github/.github/workflows/release-java17-nf.yml@main
    secrets: inherit
    with:
      mod_name: "AppliedElemental"
      curseforge_id: "1011777"
      modrinth_id: "X03FKEuI"
      dependencies: |
        ae2(required){curseforge:223794}{modrinth:XxWD5pD3}
        elementalcraft(required){curseforge:395158}{modrinth:o51LXm0t}
      target_version: ${{ github.event.inputs.target_version }}
      update_type: ${{ github.event.inputs.update_type }}
      release_type: ${{ github.event.inputs.release_type }}
      loaders: "neoforge"
      debug: ${{ github.event.inputs.debug }}
